### ISSUE TITLE
org-fc hydra taking over keymap

### ISSUE THREAD

**Issue by jethrokuan** [l3kn/org-fc#13] opened 2020-02-28 17:02 UTC
Sometimes when I exist a flashcard review session abnormally, the `org-fc-hydra` keymap is still active, and I can't disable it. That makes crucial keys like `<RET>` unavailable. Have you faced this before, and how do you get around it?

**Comment by l3kn** [comment] 2020-02-28 17:27
I've run into this a few times, ignoring unknown keys in the hydras solved it for me.

What kinds of abnormal exists do you mean?

**Comment by l3kn** [comment] 2020-02-28 17:30
In the long term, I'd like to replace the hydras with some small custom mode,
that would make it possible for card types to register their own special hotkeys
(e.g. a card type that plays audio could add a "replay" button to the rating hydra).

**Comment by jethrokuan** [comment] 2020-02-28 17:37
> ignoring unknown keys in the hydras solved it for me.

How do you do this?

 > What kinds of abnormal exists do you mean?

Sometimes the review sessions quits when I press a wrong key, and sometimes it happens even when I press `q`. It feels like a problem with hydra.

**Comment by l3kn** [comment] 2020-02-28 17:45
The `:foreign-keys warn` in https://github.com/l3kn/org-fc/blob/master/org-fc-review.el#L172 should prevent wrong keys from quitting the session, do you get a warning message when pressing an unbound key during review?

**Comment by jethrokuan** [comment] 2020-02-28 19:13
Yes, for the most part. I think the keys were pressed while I'm in some other active buffer, or it could be regular commands like `C-g`. I'll get back when I'm more clear on what happened

**Comment by l3kn** [comment] 2020-03-10 15:17
The best solution I could come up with so far is introducing two minor modes,
one for viewing (flipping) a card and one for rating it.
This should avoid issues with keybindings sticking around after a review has ended.

One problem with this is that in my setup, evil mode shadows some of the current review keys
(e.g. `n`). A workaround would be to disable evil mode during review.

@jethrokuan do you have any other ideas?

**Comment by jethrokuan** [comment] 2020-03-10 16:24
Would it not be possible to have 1 global minor mode?

This mode is toggled when along with review status (active/inactive). Keybindings are bound to this minor mode. Have a variable indicating status (flipped/not-flipped), and the keybinding calls a different function based on this variable, if need be.

**Comment by l3kn** [comment] 2020-03-10 16:38
Combining both modes into one is a good idea!

The remaining issue would be which key bindings to use,
maybe somethink like `C-f f` to flip, `C-f q` to quit the review, `C-f a/h/g/e` for rating.

Additional information (cards remaining, review history) could be shown either in the modeline or in in the windows title.

This makes review less ergonomic because it doubles the number of keystrokes required.
Users could then define their own keys and make sure
(e.g. using a hook to disable evil-mode) no other mode shadows them.

**Comment by jethrokuan** [comment] 2020-03-10 16:40
`C-f` is `forward-word`, very common keybinding. I think you can make everything read-only, and just use `f`, `q` etc. I don't want to be accidentally editing any files while doing a review.

**Comment by l3kn** [comment] 2020-05-22 13:20
I've noticed the `org-fc-hydra` was missing an `:exit t` when starting a review,
having two hydras open at the same time might have been the cause of this issue.

**Comment by l3kn** [comment] 2020-05-29 21:54
The `:exit t` might have fixed this,
I've not run into this problem since then.

Closing until there is a way to reproduce the issue.

**Closed by l3kn** 2020-05-29 21:54 UTC
